name: Bilibili Daily Checkin

on:
  schedule:
    - cron: '0 3 * * *'  # UTC时间每天3点执行(对应CST时间 11:00)
  workflow_dispatch:  # 支持手动触发

jobs:
  run-bilibili-task:
    runs-on: self-hosted
    
    steps:
      - name: Set Git Proxy
        run: |
          /usr/bin/git config --global http.proxy "http://127.0.0.1:1080"
          /usr/bin/git config --global https.proxy "http://127.0.0.1:1081"
      
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests loguru
          
      - name: Execution Information
        env:
          BILIBILI_COOKIE: ${{ secrets.BILIBILI_COOKIE }}
        run: python auto_task.py
